version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@types/matter-js"
    versions:
    - 0.14.10
  - dependency-name: yalc
    versions:
    - 1.0.0-pre.50
  - dependency-name: matter-js
    versions:
    - 0.16.0
  - dependency-name: tslib
    versions:
    - 2.1.0
